project:
  type: website

website:
  title: "yaUsername"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yausername2
format:
  html:
    theme:
      dark: [cosmo, theme-dark.scss]
      light: [cosmo]
    css: styles.css



